data: '/home/linjunyang/giga/data/'
logF: 'experiments/'
epoch: 20
batch_size: 64
optim: 'adam'
cell: 'lstm'
attention: 'luong_gate'
learning_rate: 0.0003
max_grad_norm: 10
learning_rate_decay: 0.5
start_decay_at: 1
emb_size: 512
hidden_size: 512
dec_num_layers: 2
enc_num_layers: 3
res_layers: 1
bidirectional: True
dropout: 0.1
max_time_step: 50
eval_interval: 5000
save_interval: 1000
metrics: ['rouge']
shared_vocab: True
beam_size: 10
unk: True
schedule: False
resRNN: False
selfatt: False
attemb: False
hops: 1
schesamp: False
swish: True
